export enum reduxActionTypes {
    FETCH_USER_REQUEST = "FETCH_USER_REQUEST",
    FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS",
    FETCH_ORDER_REQUEST = "FETCH_ORDER_REQUEST",
    FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS"
}